# env realted
cuda: [ '1']

cfg_name: "scannet_mvdnet"

# dataset related
dataset: 'scannet'
dataset_path: '/6t/jty/scannet/'
num_workers: 16
train_list: './data/train1.txt'
test_list: './data/val1.txt'
dataloader: 'SequenceFolder'

# training related
batch_size: 4
epochs: 35
learning_rate: 0.0002
momentum: 0.9
beta: 0.999
weight_decay: 0
print_freq: 20
# training utils used
depth_fliter_by_multi_views: {use: False, valid_threshod: 0.1 }
training_weight_schedule: False

# model related
model_name: 'MVDNet_nslpn'
ndepth: 64
mindepth: 0.5
maxdepth: 10.0
conf_dgamma: 5.0
conf_ngamma: 5.0
prop_kernel: 3
num_neighbors: 8
affinity: 'TGASS'
conf_prop: False
affinity_gamma: 0.5
preserve_input: False
prop_time: 5 # iterations of solver
pretrained_mvdn: "/home/jty/mvs/idn-solver/results/stage1/checkpoints/checkpoint.pth.tar"

# loss related
d_weight: 0.7 # depth loss weight of the first term
n_weight: 3.0 # normal loss weight
nc_weight: 0.2 # normal confidence loss weight
dc_weight: 0.2 # depth confidence loss weight

# logging related
log_mode: 'summary' # or 'full'
output_dir: './resultsnew/MVDNet_nslpntest/'
save_samples: True


