cfg_name: "folder_mvdnet"
reference_gap: 1

# model related
input_size: [480,640]
model_name: 'MVDNet_conf'
ndepth: 64
mindepth: 0.5
maxdepth: 10.0
conf_dgamma: 5.0
conf_ngamma: 5.0
check_offsets: [1,3,5,10]
solver_alpha1: 1.0
solver_alpha2: 1.0
solver_sigma1: 50.0
solver_sigma2: 5.0
refine_iter: 25 # iterations of solver

# nslpon
prop_kernel: 3
num_neighbors: 8
affinity: 'TGASS'
conf_prop: False
affinity_gamma: 0.5
preserve_input: False
prop_time: 25 # iterations of solver

use_aff: True
with_sommth: False
afftype: ''

# pretrained_mvdn: "./pretrain/checkpoint.pth.tar"

# pretrained_mvdn: "results/stage1/checkpoints/mvdnet_14_checkpoint.pth.tar"
# pretrained_mvdn: "results/stage2/checkpoints/mvdnet_9_checkpoint.pth.tar"

pretrained_mvdn: "/home/jty/mvs/idn-solver/results/MVDNet_propddp2/checkpoints/mvdnet_13_checkpoint.pth.tar"

